/**
 * D1 Seed Data Export Script
 * 
 * **D1-FIRST POLICY**
 * Exports seed data as SQL format suitable for D1 injection.
 * This creates SQL INSERT statements that can be executed via wrangler.
 * 
 * Usage:
 *   pnpm db:export-seed
 *   wrangler d1 execute document-reception-system --remote --file=./seed-export.sql
 */

import { randomUUID } from 'crypto';
import bcrypt from 'bcryptjs';
import * as fs from 'fs';
import * as path from 'path';

console.log('📦 D1シードデータをエクスポート中...');
console.log('');

async function exportSeed() {
  const sqlStatements: string[] = [];
  
  // Helper function to escape SQL string values
  const escapeSqlString = (str: string): string => {
    return str.replace(/'/g, "''");
  };
  
  // ヘッダーコメント
  sqlStatements.push('-- D1 Seed Data Export');
  sqlStatements.push('-- Generated at: ' + new Date().toISOString());
  sqlStatements.push('-- DO NOT EDIT THIS FILE MANUALLY');
  sqlStatements.push('');
  
  try {
    // 1. ワークフローテンプレート
    console.log('📋 ワークフローテンプレートをエクスポート中...');
    const workflowTemplateId = randomUUID();
    sqlStatements.push('-- Workflow Templates');
    sqlStatements.push(
      `INSERT INTO workflow_templates (id, name, statuses, created_at, updated_at) VALUES ('${workflowTemplateId}', '${escapeSqlString('標準ワークフロー')}', '${escapeSqlString(JSON.stringify(['受付', '処理中', '検査', '完了']))}', datetime('now'), datetime('now'));`
    );
    sqlStatements.push('');

    // 2. 部署
    console.log('🏢 部署データをエクスポート中...');
    const deptIds = {
      general: randomUUID(),
      engineering: randomUUID(),
      inspection: randomUUID(),
      management: randomUUID(),
    };

    sqlStatements.push('-- Departments');
    sqlStatements.push(
      `INSERT INTO departments (id, code, name, parent_id, is_active, sort_order, created_at, updated_at) VALUES ('${deptIds.general}', 'DEPT001', '${escapeSqlString('総務部')}', NULL, 1, 1, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO departments (id, code, name, parent_id, is_active, sort_order, created_at, updated_at) VALUES ('${deptIds.engineering}', 'DEPT002', '${escapeSqlString('工務部')}', NULL, 1, 2, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO departments (id, code, name, parent_id, is_active, sort_order, created_at, updated_at) VALUES ('${deptIds.inspection}', 'DEPT003', '${escapeSqlString('検査部')}', NULL, 1, 3, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO departments (id, code, name, parent_id, is_active, sort_order, created_at, updated_at) VALUES ('${deptIds.management}', 'DEPT004', '${escapeSqlString('管理部')}', NULL, 1, 4, datetime('now'), datetime('now'));`
    );
    sqlStatements.push('');

    // 3. ユーザー
    console.log('👤 ユーザーデータをエクスポート中...');
    const userIds = {
      admin: randomUUID(),
      senior: randomUUID(),
      general: randomUUID(),
    };

    // パスワード: password123 をハッシュ化
    const defaultPasswordHash = await bcrypt.hash('password123', 10);

    sqlStatements.push('-- Users');
    sqlStatements.push(
      `INSERT INTO users (id, username, password_hash, display_name, role, department_id, is_active, created_at, updated_at) VALUES ('${userIds.admin}', 'admin', '${escapeSqlString(defaultPasswordHash)}', '${escapeSqlString('管理者ユーザー')}', 'ADMIN', '${deptIds.management}', 1, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO users (id, username, password_hash, display_name, role, department_id, is_active, created_at, updated_at) VALUES ('${userIds.senior}', 'senior1', '${escapeSqlString(defaultPasswordHash)}', '${escapeSqlString('上位ユーザー')}', 'SENIOR', '${deptIds.engineering}', 1, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO users (id, username, password_hash, display_name, role, department_id, is_active, created_at, updated_at) VALUES ('${userIds.general}', 'user1', '${escapeSqlString(defaultPasswordHash)}', '${escapeSqlString('一般ユーザー')}', 'GENERAL', '${deptIds.general}', 1, datetime('now'), datetime('now'));`
    );
    sqlStatements.push('');

    // 4. 届出グループと届出種類
    console.log('📄 届出グループと届出種類データをエクスポート中...');
    
    // 届出グループID
    const notificationGroupIds = {
      construction: randomUUID(), // 工事関連
      administrative: randomUUID(), // 事務手続き関連
    };
    
    const notificationTypeIds = {
      // 工事関連グループの届出種別
      newConstruction: randomUUID(),
      repair: randomUUID(),
      demolition: randomUUID(),
      // 事務手続き関連グループの届出種別
      inspection: randomUUID(),
      report: randomUUID(),
    };

    sqlStatements.push('-- Notification Groups（届出グループ）');
    sqlStatements.push(
      `INSERT INTO notification_groups (id, code, name, description, is_active, sort_order, created_at, updated_at) VALUES ('${notificationGroupIds.construction}', 'NTG001', '${escapeSqlString('工事関連')}', '${escapeSqlString('工事に関する届出グループ')}', 1, 1, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_groups (id, code, name, description, is_active, sort_order, created_at, updated_at) VALUES ('${notificationGroupIds.administrative}', 'NTG002', '${escapeSqlString('事務手続き関連')}', '${escapeSqlString('事務手続きに関する届出グループ')}', 1, 2, datetime('now'), datetime('now'));`
    );
    sqlStatements.push('');

    sqlStatements.push('-- Notification Types（届出種別）');
    // 工事関連の届出種別
    sqlStatements.push(
      `INSERT INTO notification_types (id, code, name, description, group_id, has_inspection, has_content_field, requires_additional_data, workflow_template_id, is_active, sort_order, created_at, updated_at) VALUES ('${notificationTypeIds.newConstruction}', 'NT001', '${escapeSqlString('新築工事届')}', '${escapeSqlString('新築工事に関する届出')}', '${notificationGroupIds.construction}', 1, 1, 1, '${workflowTemplateId}', 1, 1, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_types (id, code, name, description, group_id, has_inspection, has_content_field, requires_additional_data, workflow_template_id, is_active, sort_order, created_at, updated_at) VALUES ('${notificationTypeIds.repair}', 'NT002', '${escapeSqlString('修繕工事届')}', '${escapeSqlString('修繕工事に関する届出')}', '${notificationGroupIds.construction}', 1, 1, 0, '${workflowTemplateId}', 1, 2, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_types (id, code, name, description, group_id, has_inspection, has_content_field, requires_additional_data, workflow_template_id, is_active, sort_order, created_at, updated_at) VALUES ('${notificationTypeIds.demolition}', 'NT003', '${escapeSqlString('解体工事届')}', '${escapeSqlString('解体工事に関する届出')}', '${notificationGroupIds.construction}', 1, 1, 1, '${workflowTemplateId}', 1, 3, datetime('now'), datetime('now'));`
    );
    // 事務手続き関連の届出種別
    sqlStatements.push(
      `INSERT INTO notification_types (id, code, name, description, group_id, has_inspection, has_content_field, requires_additional_data, workflow_template_id, is_active, sort_order, created_at, updated_at) VALUES ('${notificationTypeIds.inspection}', 'NT004', '${escapeSqlString('検査依頼')}', '${escapeSqlString('検査に関する依頼')}', '${notificationGroupIds.administrative}', 0, 1, 0, '${workflowTemplateId}', 1, 4, datetime('now'), datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_types (id, code, name, description, group_id, has_inspection, has_content_field, requires_additional_data, workflow_template_id, is_active, sort_order, created_at, updated_at) VALUES ('${notificationTypeIds.report}', 'NT005', '${escapeSqlString('完了報告')}', '${escapeSqlString('工事完了に関する報告')}', '${notificationGroupIds.administrative}', 0, 1, 0, '${workflowTemplateId}', 1, 5, datetime('now'), datetime('now'));`
    );
    sqlStatements.push('');

    // 5. サンプル届出データ
    console.log('📝 サンプル届出データをエクスポート中...');
    const notificationIds = {
      notification1: randomUUID(),
      notification2: randomUUID(),
      notification3: randomUUID(),
    };

    const today = new Date().toISOString().split('T')[0];
    const futureDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
    const pastDate = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

    // 追加データのサンプル（JSON形式）
    const additionalDataSample1 = JSON.stringify({
      buildingStructure: '鉄筋コンクリート造',
      floors: 3,
      totalArea: 250.5,
      constructionCompany: 'ABC建設株式会社',
      estimatedCost: 50000000,
    });
    
    const additionalDataSample2 = JSON.stringify({
      demolitionMethod: '機械解体',
      asbestosPresent: false,
      estimatedDuration: 30,
      wasteDisposalPlan: '産業廃棄物処理業者に委託',
    });

    sqlStatements.push('-- Notifications');
    // 届出1: 新築工事届（追加データあり）
    sqlStatements.push(
      `INSERT INTO notifications (id, notification_type_id, notification_date, receiving_department_id, processing_department_id, property_name, content, additional_data, inspection_date, inspection_department_id, completion_date, current_status, created_by, created_at, updated_at, updated_by) VALUES ('${notificationIds.notification1}', '${notificationTypeIds.newConstruction}', '${today}', '${deptIds.general}', '${deptIds.engineering}', '${escapeSqlString('サンプル物件A')}', '${escapeSqlString('新築工事の届出です')}', '${escapeSqlString(additionalDataSample1)}', NULL, NULL, NULL, '${escapeSqlString('受付')}', '${userIds.general}', datetime('now'), datetime('now'), '${userIds.general}');`
    );
    // 届出2: 修繕工事届（追加データなし）
    sqlStatements.push(
      `INSERT INTO notifications (id, notification_type_id, notification_date, receiving_department_id, processing_department_id, property_name, content, additional_data, inspection_date, inspection_department_id, completion_date, current_status, created_by, created_at, updated_at, updated_by) VALUES ('${notificationIds.notification2}', '${notificationTypeIds.repair}', '${today}', '${deptIds.general}', '${deptIds.engineering}', '${escapeSqlString('サンプル物件B')}', '${escapeSqlString('外壁修繕の届出です')}', NULL, NULL, NULL, NULL, '${escapeSqlString('処理中')}', '${userIds.general}', datetime('now'), datetime('now'), '${userIds.senior}');`
    );
    // 届出3: 解体工事届（追加データあり）
    sqlStatements.push(
      `INSERT INTO notifications (id, notification_type_id, notification_date, receiving_department_id, processing_department_id, property_name, content, additional_data, inspection_date, inspection_department_id, completion_date, current_status, created_by, created_at, updated_at, updated_by) VALUES ('${notificationIds.notification3}', '${notificationTypeIds.demolition}', '${pastDate}', '${deptIds.general}', '${deptIds.engineering}', '${escapeSqlString('サンプル物件C')}', '${escapeSqlString('老朽化建物の解体工事')}', '${escapeSqlString(additionalDataSample2)}', NULL, NULL, NULL, '${escapeSqlString('検査')}', '${userIds.general}', datetime('now'), datetime('now'), '${userIds.senior}');`
    );
    sqlStatements.push('');

    // 6. 検査データ
    console.log('🔍 検査データをエクスポート中...');
    const inspectionIds = {
      inspection1: randomUUID(),
      inspection2: randomUUID(),
      inspection3: randomUUID(),
    };

    sqlStatements.push('-- Inspections');
    // 届出1に対する検査（中間検査）
    sqlStatements.push(
      `INSERT INTO inspections (id, notification_id, inspection_date, inspection_department_id, inspection_type, status, result, notes, inspected_by, inspected_at, created_by, created_at, updated_at, updated_by) VALUES ('${inspectionIds.inspection1}', '${notificationIds.notification1}', '${futureDate}', '${deptIds.inspection}', '${escapeSqlString('中間検査')}', '${escapeSqlString('予定')}', NULL, '${escapeSqlString('基礎工事完了後に実施予定')}', NULL, NULL, '${userIds.senior}', datetime('now'), datetime('now'), '${userIds.senior}');`
    );
    // 届出2に対する検査（完了検査）
    sqlStatements.push(
      `INSERT INTO inspections (id, notification_id, inspection_date, inspection_department_id, inspection_type, status, result, notes, inspected_by, inspected_at, created_by, created_at, updated_at, updated_by) VALUES ('${inspectionIds.inspection2}', '${notificationIds.notification2}', '${futureDate}', '${deptIds.inspection}', '${escapeSqlString('完了検査')}', '${escapeSqlString('予定')}', NULL, '${escapeSqlString('修繕工事完了後に検査を実施')}', NULL, NULL, '${userIds.senior}', datetime('now'), datetime('now'), '${userIds.senior}');`
    );
    // 届出3に対する検査（解体前検査 - 実施済み）
    sqlStatements.push(
      `INSERT INTO inspections (id, notification_id, inspection_date, inspection_department_id, inspection_type, status, result, notes, inspected_by, inspected_at, created_by, created_at, updated_at, updated_by) VALUES ('${inspectionIds.inspection3}', '${notificationIds.notification3}', '${pastDate}', '${deptIds.inspection}', '${escapeSqlString('解体前検査')}', '${escapeSqlString('実施済み')}', '${escapeSqlString('合格')}', '${escapeSqlString('アスベストなし、解体作業可')}', '${userIds.senior}', datetime('now'), '${userIds.senior}', datetime('now'), datetime('now'), '${userIds.senior}');`
    );
    sqlStatements.push('');

    // 7. 届出履歴
    console.log('📊 届出履歴データをエクスポート中...');
    sqlStatements.push('-- Notification History');
    sqlStatements.push(
      `INSERT INTO notification_history (id, notification_id, status_from, status_to, changed_by, comment, changed_at) VALUES ('${randomUUID()}', '${notificationIds.notification1}', NULL, '${escapeSqlString('受付')}', '${userIds.general}', '${escapeSqlString('新規届出受付')}', datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_history (id, notification_id, status_from, status_to, changed_by, comment, changed_at) VALUES ('${randomUUID()}', '${notificationIds.notification2}', NULL, '${escapeSqlString('受付')}', '${userIds.general}', '${escapeSqlString('新規届出受付')}', datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_history (id, notification_id, status_from, status_to, changed_by, comment, changed_at) VALUES ('${randomUUID()}', '${notificationIds.notification2}', '${escapeSqlString('受付')}', '${escapeSqlString('処理中')}', '${userIds.senior}', '${escapeSqlString('処理を開始しました')}', datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_history (id, notification_id, status_from, status_to, changed_by, comment, changed_at) VALUES ('${randomUUID()}', '${notificationIds.notification3}', NULL, '${escapeSqlString('受付')}', '${userIds.general}', '${escapeSqlString('新規届出受付')}', datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_history (id, notification_id, status_from, status_to, changed_by, comment, changed_at) VALUES ('${randomUUID()}', '${notificationIds.notification3}', '${escapeSqlString('受付')}', '${escapeSqlString('処理中')}', '${userIds.senior}', '${escapeSqlString('処理を開始しました')}', datetime('now'));`
    );
    sqlStatements.push(
      `INSERT INTO notification_history (id, notification_id, status_from, status_to, changed_by, comment, changed_at) VALUES ('${randomUUID()}', '${notificationIds.notification3}', '${escapeSqlString('処理中')}', '${escapeSqlString('検査')}', '${userIds.senior}', '${escapeSqlString('検査段階に移行')}', datetime('now'));`
    );
    sqlStatements.push('');

    // SQLファイルに書き出し
    const outputPath = path.join(process.cwd(), 'seed-export.sql');
    fs.writeFileSync(outputPath, sqlStatements.join('\n'), 'utf-8');

    console.log('✅ エクスポート完了！');
    console.log(`📁 出力先: ${outputPath}`);
    console.log('');
    console.log('📌 D1への投入方法:');
    console.log('  # ローカルD1でテスト:');
    console.log('  wrangler d1 execute document-reception-system --local --file=./seed-export.sql');
    console.log('');
    console.log('  # 本番D1に投入:');
    console.log('  wrangler d1 execute document-reception-system --remote --file=./seed-export.sql');
    console.log('');
    console.log('📌 初期ユーザー情報:');
    console.log('  管理者: username=admin, password=password123');
    console.log('  上位ユーザー: username=senior1, password=password123');
    console.log('  一般ユーザー: username=user1, password=password123');
  } catch (error) {
    console.error('❌ エクスポート中にエラーが発生しました:', error);
    throw error;
  }
}

// スクリプト実行
exportSeed()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
